apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-springboot
spec:
  replicas: 0
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: selmaguedidi/devops-integration:latest
          ports:
            - containerPort: 8080
