apiVersion: v1
kind: Service
metadata:
  name: springboot-service-lb
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
